import type { ResourceConfig } from './types';

const setorRelation = {
  endpoint: '/setor/setores/',
  idField: 'id_setor',
  labelField: 'nome',
};

const cargoRelation = {
  endpoint: '/setor/cargos/',
  idField: 'id_cargo',
  labelField: 'nome',
  secondaryFields: ['fk_id_setor'],
};

const funcionarioRelation = {
  endpoint: '/funcionario/funcionarios/',
  idField: 'id_funcionario',
  labelField: 'nome',
  secondaryFields: ['fk_id_cargo'],
};

export const resources = {
  setores: {
    title: 'Setores',
    description: 'Cadastro e acompanhamento dos setores da organização.',
    endpoint: '/setor/setores/',
    idField: 'id_setor',
    columns: [
      { key: 'id_setor', label: 'ID' },
      { key: 'nome', label: 'Nome' },
      { key: 'descricao', label: 'Descrição' },
    ],
    fields: [
      { name: 'nome', label: 'Nome', required: true },
      { name: 'descricao', label: 'Descrição', type: 'textarea' },
    ],
    allowCreate: true,
    allowEdit: true,
    allowDelete: true,
  },
  cargos: {
    title: 'Cargos',
    description: 'Gestão dos cargos, suas descrições e o setor responsável.',
    endpoint: '/setor/cargos/',
    idField: 'id_cargo',
    columns: [
      { key: 'id_cargo', label: 'ID' },
      { key: 'nome', label: 'Nome' },
      { key: 'fk_id_setor', label: 'Setor' },
      { key: 'descricao', label: 'Descrição' },
    ],
    fields: [
      { name: 'nome', label: 'Nome', required: true },
      { name: 'fk_id_setor', label: 'Setor', required: true, relation: setorRelation },
      { name: 'descricao', label: 'Descrição', type: 'textarea' },
    ],
    allowCreate: true,
    allowEdit: true,
    allowDelete: true,
  },
  funcionarios: {
    title: 'Funcionários',
    description: 'Gestão administrativa de funcionários, acesso ao sistema, vínculos e cargos.',
    endpoint: '/funcionario/funcionarios/',
    idField: 'id_funcionario',
    columns: [
      { key: 'id_funcionario', label: 'ID' },
      { key: 'nome', label: 'Nome' },
      { key: 'username', label: 'Usuário' },
      { key: 'cpf', label: 'CPF' },
      { key: 'email', label: 'E-mail' },
      { key: 'fk_id_setor', label: 'Setor' },
      { key: 'fk_id_cargo', label: 'Cargo' },
      { key: 'status', label: 'Status' },
      { key: 'is_active', label: 'Acesso ativo' },
    ],
    fields: [
      { name: 'username', label: 'Usuário de acesso', required: true },
      { name: 'password', label: 'Senha inicial ou nova senha', type: 'password' },
      { name: 'nome', label: 'Nome', required: true },
      { name: 'cpf', label: 'CPF', required: true },
      { name: 'email', label: 'E-mail', type: 'email' },
      { name: 'telefone', label: 'Telefone' },
      { name: 'data_admissao', label: 'Data de admissão', type: 'date', required: true },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Ativo', value: 'ativo' },
          { label: 'Inativo', value: 'inativo' },
        ],
      },
      {
        name: 'is_staff',
        label: 'Administrador',
        type: 'select',
        options: [
          { label: 'Não', value: 'false' },
          { label: 'Sim', value: 'true' },
        ],
      },
      { name: 'fk_id_cargo', label: 'Cargo', required: true, relation: cargoRelation },
    ],
    allowCreate: true,
    allowEdit: true,
    allowDelete: true,
  },
  usuarios: {
    title: 'Usuários',
    description: 'Usuários criados no sistema e seus dados principais.',
    endpoint: '/auth/usuarios/',
    idField: 'id',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'nome', label: 'Nome' },
      { key: 'username', label: 'Usuário' },
      { key: 'email', label: 'E-mail' },
      { key: 'telefone', label: 'Telefone' },
      { key: 'is_active', label: 'Ativo' },
      { key: 'is_staff', label: 'Admin' },
    ],
    fields: [
      { name: 'username', label: 'Usuário', required: true },
      { name: 'nome', label: 'Nome' },
      { name: 'email', label: 'E-mail', type: 'email' },
      { name: 'telefone', label: 'Telefone' },
      {
        name: 'is_active',
        label: 'Ativo',
        type: 'select',
        options: [
          { label: 'Sim', value: 'true' },
          { label: 'Não', value: 'false' },
        ],
      },
      {
        name: 'is_staff',
        label: 'Admin',
        type: 'select',
        options: [
          { label: 'Sim', value: 'true' },
          { label: 'Não', value: 'false' },
        ],
      },
    ],
    allowCreate: false,
    allowEdit: true,
    allowDelete: true,
  },
  contratos: {
    title: 'Contratos',
    description: 'Gestão dos contratos vinculados aos funcionários.',
    endpoint: '/funcionario/contratos/',
    idField: 'id_contrato',
    columns: [
      { key: 'id_contrato', label: 'ID' },
      { key: 'fk_id_funcionario', label: 'Funcionário' },
      { key: 'tipo_contrato', label: 'Tipo' },
      { key: 'salario', label: 'Salário' },
      { key: 'data_inicio', label: 'Início' },
      { key: 'data_fim', label: 'Fim' },
    ],
    fields: [
      { name: 'fk_id_funcionario', label: 'Funcionário', required: true, relation: funcionarioRelation },
      { name: 'tipo_contrato', label: 'Tipo de contrato' },
      { name: 'salario', label: 'Salário', type: 'number' },
      { name: 'data_inicio', label: 'Data de início', type: 'date', required: true },
      { name: 'data_fim', label: 'Data de fim', type: 'date' },
    ],
    allowCreate: true,
    allowEdit: true,
    allowDelete: true,
  },
  planos: {
    title: 'Planos de carreira',
    description: 'Planos vinculados aos cargos e trajetórias funcionais.',
    endpoint: '/funcionario/planos-carreira/',
    idField: 'id_plano',
    columns: [
      { key: 'id_plano', label: 'ID' },
      { key: 'fk_id_cargo', label: 'Cargo' },
      { key: 'descricao', label: 'Descrição' },
      { key: 'requisitos', label: 'Requisitos' },
    ],
    fields: [
      { name: 'fk_id_cargo', label: 'Cargo', required: true, relation: cargoRelation },
      { name: 'descricao', label: 'Descrição', type: 'textarea' },
      { name: 'requisitos', label: 'Requisitos', type: 'textarea' },
    ],
    allowCreate: true,
    allowEdit: true,
    allowDelete: true,
  },
  avaliacoes: {
    title: 'Avaliações de desempenho',
    description: 'Avaliações, notas e comentários conforme permissões da API.',
    endpoint: '/avaliacao/avaliacoes-desempenho/',
    idField: 'id_avaliacao',
    columns: [
      { key: 'id_avaliacao', label: 'ID' },
      { key: 'fk_id_funcionario', label: 'Funcionário' },
      { key: 'fk_id_avaliador', label: 'Avaliador' },
      { key: 'categoria', label: 'Categoria' },
      { key: 'nota', label: 'Nota' },
      { key: 'data_avaliacao', label: 'Data' },
    ],
    fields: [
      { name: 'fk_id_funcionario', label: 'Funcionário avaliado', required: true, relation: funcionarioRelation },
      { name: 'fk_id_avaliador', label: 'Avaliador', required: true, relation: funcionarioRelation },
      { name: 'categoria', label: 'Categoria' },
      { name: 'nota', label: 'Nota', type: 'number' },
      { name: 'comentario', label: 'Comentário', type: 'textarea' },
      { name: 'data_avaliacao', label: 'Data da avaliação', type: 'date', required: true },
    ],
    allowCreate: true,
    allowEdit: true,
    allowDelete: true,
  },
  analises: {
    title: 'Análises comportamentais',
    description: 'Gestão de análises comportamentais por funcionário.',
    endpoint: '/avaliacao/analises-comportamentais/',
    idField: 'id_analise',
    columns: [
      { key: 'id_analise', label: 'ID' },
      { key: 'fk_id_funcionario', label: 'Funcionário' },
      { key: 'resultado', label: 'Resultado' },
      { key: 'data_analise', label: 'Data' },
    ],
    fields: [
      { name: 'fk_id_funcionario', label: 'Funcionário', required: true, relation: funcionarioRelation },
      { name: 'resultado', label: 'Resultado', type: 'textarea' },
      { name: 'data_analise', label: 'Data da análise', type: 'date' },
    ],
    allowCreate: true,
    allowEdit: true,
    allowDelete: true,
  },
  vagas: {
    title: 'Vagas',
    description: 'Gestão de vagas e processos seletivos.',
    endpoint: '/candidato/vagas/',
    idField: 'id_vaga',
    columns: [
      { key: 'id_vaga', label: 'ID' },
      { key: 'titulo', label: 'Título' },
      { key: 'descricao', label: 'Descrição' },
      { key: 'data_publicacao', label: 'Publicação' },
      { key: 'fk_id_setor', label: 'Setor' },
    ],
    fields: [
      { name: 'titulo', label: 'Título' },
      { name: 'descricao', label: 'Descrição', type: 'textarea' },
      { name: 'data_publicacao', label: 'Data de publicação', type: 'date' },
      { name: 'fk_id_setor', label: 'Setor', relation: setorRelation },
    ],
    allowCreate: true,
    allowEdit: true,
    allowDelete: true,
  },
  candidatosAdmin: {
    title: 'Candidatos',
    description: 'Consulta administrativa de candidatos e currículos conforme permissão.',
    endpoint: '/candidato/candidatos/',
    idField: 'cpf_candidato',
    columns: [
      { key: 'cpf_candidato', label: 'CPF' },
      { key: 'nome', label: 'Nome' },
      { key: 'email', label: 'E-mail' },
      { key: 'telefone', label: 'Telefone' },
      { key: 'curriculo', label: 'Currículo' },
    ],
    fields: [],
    allowCreate: false,
    allowEdit: false,
    allowDelete: true,
  },
} satisfies Record<string, ResourceConfig>;
